version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dbscript/init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init.sql script

volumes:
  postgres_data: