version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dbscript/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - server-net

  app:
    build:
      context: .
    environment:
      - POSTGRES_CONNECTION_STRING=postgres://user:password@postgres:5432/payment?sslmode=disable
      - GATEWAY_A_URL=http://host.docker.internal:3000/json
      - GATEWAY_B_URL=http://host.docker.internal:3000/xml
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - server-net


volumes:
  postgres_data:

networks:
  server-net:
    driver: bridge